channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - pip=20.1.1
  - python=3.7.3
  - pytorch=1.8.0
  - python-blosc=1.7.0
  - torchvision=0.9.0
  - pip:
      - azure-mgmt-datafactory==1.1.0
      - azure-mgmt-resource<15.0.0,>=1.2.1
      - azureml-cli-common>=1.31.0
      - azureml-core>=1.31.0
      - azureml-dataset-runtime>=1.31.0
      - azureml-mlflow>=1.31.0
      - azureml-sdk>=1.31.0
      - azureml-telemetry>=1.31.0
      - azureml-tensorboard>=1.31.0
      - azureml-train>=1.31.0
      - azureml-widgets>=1.31.0
      - ipykernel==6.3.1
      - jupyter-client==6.1.5
      - jupyter==1.0.0
      - lightning-bolts==0.3.4
      - matplotlib==3.2.1
      - mlflow>=1.17.0
      - mypy==0.812
      - numba==0.51.2
      - numpy<1.19.3
      - opencv-python-headless==4.5.1.48
      - pandas==1.1.5
      - param==1.9.3
      - pillow==8.2.0
      - plotly==5.3.1
      - pytorch-lightning==1.4.7
      - scikit-image==0.17.2
      - scikit-learn==0.24.2
      - scipy==1.7.0
      - seaborn==0.11.2
      - sklearn-pandas==2.2.0
      - tabulate==0.8.7
      - tensorboard==2.3.0
      - torchmetrics==0.4.1
      - torchprof==1.3.3
      - tqdm>=4.59,<4.60
      - environs==9.3.3
