name: PR BuildAndTest.CI
on:
  push:
    branches: [main]
    tags:
      - "*"
  pull_request:
    branches: [main]

env:
  pythonVersion: 3.7

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up Python ${{ env.pythonVersion }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.pythonVersion }}

      - name: Install Python dependencies
        run: pip install black flake8

      # - name: flake8
      #   run: flake8 .
